name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Spring Boot application with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker Build
        run: |
          docker build -t doyu301/myapp ./
          docker tag doyu301/myapp:latest doyu301/myapp:${{ github.sha }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Push
        run: docker push doyu301/myapp:${{ github.sha }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: spring-docker
          environment_name: Spring-docker-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-637423306910
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          wait_for_deploy: true
